-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "amount" SET DEFAULT '0',
ALTER COLUMN "amount" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Wallet" ALTER COLUMN "balance" SET DEFAULT '0',
ALTER COLUMN "balance" SET DATA TYPE TEXT;
